### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by matteodefelice** [noeliaof/SEI#1]
Hi, thanks for sharing the package. As far as I understand, the vignette is the only documentation (tutorial) available for this package, is this correct? Unfortunately, I cannot compile the vignette from R (it doesn't see it). Can you share the PDF (or a markdown on Github) or some more detailed instructions on how to compile the vignette?

**Comment by sallen12** [comment]
Hi, thanks a lot for pointing this out. The vignette is currently the only documentation available for this package. We have shared the PDF for now and will hopefully resolve the issue shortly. Let us know if anything is unclear.

**Comment by sallen12** [comment]
To see the vignette you need to install the package using 
devtools::install_github("noeliaof/SEI", build_vignettes = T)

I've now added this to the readme file. Thanks again
